### ISSUE TITLE
Create github actions

### ISSUE THREAD

**Issue by glanderson42** [glanderson42/gomk#19]

**Comment by CypherpunkSamurai** [comment]
Hello 👋🏼,
Can I work on this issue as a part of hacktoberfest? :)

**Comment by glanderson42** [comment]
Hi!
yes, of course :)

**Comment by CypherpunkSamurai** [comment]
Ok. as I understand from the Issue we are supposed to write a github actions template to automate running gomk right @glanderson42?

**Comment by glanderson42** [comment]
Yes. It should run on every pr for main. It should contain `go build` and `go test` commands.

**Comment by CypherpunkSamurai** [comment]
Hello @glanderson42, I've added a PR. Please review changes :)
